### ISSUE TITLE
res.on('metadata' ... only fired once

### ISSUE THREAD

**Issue by secretfader** [TooTallNate/node-icy#16]
On my AAC+ stream, the metadata handler only fires once. It doesn't fire again when metadata changes. (On the OGG Vorbis stream, it doesn't fire at all.)

(Tested with the server http://live.machine.fm)

**Comment by SumitBisht** [comment]
@nicholaswyoung how did you pipe the stream in your app?

**Comment by nicholaswyoung** [comment]
@sumitbisht Google for "Node.js /dev/null" and you'll probably come across the module I used. I found a helper that made it easy.

**Comment by neilhem** [comment]
In short:
```js
var icy = require('icy');
var devnull = require('dev-null');

icy.get(url, function (res) {

    // log any "metadata" events that happen
    res.on('metadata', function (metadata) {
      const parsed = icy.parse(metadata);
      console.log('metadata', parsed);
    });

    res.pipe(devnull());
});

**Comment by TooTallNate** [comment]
You should also be able to simply call `res.resume()`.
