### ISSUE TITLE
Connection Limit?

### ISSUE THREAD

**Issue by whobutsb** [TooTallNate/node-icy#17]
Is there a connection limit to the number of icecast streams that you can connect to? I'm working on building a monitoring service where i connect to the icecast stream and then wait for the `end` event, which I then do some operations to alert the admins. 

I'm able to trigger an `end` event message for about the first 5 streams on the list.  The rest don't seem to be connecting. 

Here is an example of what I'm trying to do: 
```
// var sources is coming from the icecast stats
// go through the sources and set them up to be monitored
for(var $i = 0; $i < 50; $i++){
    var stream = sources.source[$i].listenurl;
    icecast.monitor(stream);
}

// my icecast.monitor function
// receives the streamurl / listenurl and tries to connect 
exports.monitor = function(url) {
	console.log('Monitoring: '+url); 
	icecast.get(url , function(res){
		
		// get the metadata
		res.on('metadata', function(metadata){
			var parsed = icecast.parse(metadata); 
			console.error(parsed); 
		});	

		res.on('data', function(data){
			// console.log(data); 
		}); 

		// when something goes wrong
		res.on('end', function(data){
			console.log('oh shit something went wrong with'); 
		}); 
	}); 
};
```

**Comment by aw030** [comment]
a dirty way to increase socket connections is to patch the icecast/lib/client.js by adding i.e.:
<code>http.globalAgent.maxSockets = 20;</code>

It would be great to have a possibility to pass a config to set the amount of allowed socket connections or is it already possible in a better way as the above patch?

greetings from berlin

**Comment by TooTallNate** [comment]
Send an `agent: false` option in the `icecast.get()` function in order for a new http.Agent to be used for every connection. Then this problem should not occur.

**Comment by whobutsb** [comment]
Thank you for the responses.  I haven't worked on this in a while, but I'am still heavily involved with using IceS and IceCast.  I'll let you know how it goes.
