### ISSUE TITLE
following redirect ?

### ISSUE THREAD

**Issue by hems** [TooTallNate/node-icy#23]
My icecast loadbalancer is issuing a "moved temporarily" header and pointing the stream somewhere, it seems that this is breaking the ".get" method from node-icy.

Any ideas on how to "follow redirects" ?

**Comment by TooTallNate** [comment]
Call `icecast.get(res.headers.location)`? I don't really think following redirects is in the scope of this module.

**Comment by hems** [comment]
i dropped node-icy and i'm using the "request" module instead, it's doing everything i need ( :

thanks anyway!

**Comment by hems** [comment]
````
  stream = request.get( path )

  stream.on 'response', ( response ) ->

    headers = response.headers

    if response.statusCode is 404 or headers[ 'content-type' ] isnt "audio/mpeg"

      #fail yada yada

      return 

    stream.pipe [...]
````
