### ISSUE TITLE
Anyway to increase metadata yield from stream?

### ISSUE THREAD

**Issue by PradatiusD** [TooTallNate/node-icy#24]
Hi Nathan!

First of all thank you for taking the time to write this in node!  Helpful, useful & awesome!

I wanted to understand why sometimes certain streams have empty metadata.  I understand that there is a possibility that the stream itself failed to inject metadata, but I wonder if there is anything that could be done on the Node.js client-side to increase yield of metadata.

From [ShoutCast Documentation](http://www.smackfu.com/stuff/programming/shoutcast.html):

> Read the data stream as you normally would, keeping a byte count as you go. When the number of bytes equals the metadata interval, you will get a metadata block. The first part of the block is a length specifier, which is the next byte in the stream. This byte will equal the metadata length / 16. Multiply by 16 to get the actual metadata length. (Max byte size = 255 so metadata max length = 4080.) Now read that many bytes and you will have a string containing the metadata. Restart your byte count, and repeat. Success!

I see that the module:

1. Keeps a byte count
2. Fires a metadata event as soon as the response data reaches icy-metaint interval (in cURL case below at 2048)
3. On that metadata event, uses a META_BLOCK_SIZE constant to figure out the length of the metadata, and once acquiring that length, parsing that data to get at the StreamTitle string

Yet anecdotally I get some value metadata a third or half the time.  This could (and most likely is) the server itself failing to inject that metadata into the stream, but I wonder if there is anything else that could be done on the client side.

Here is an example request/response:
```
curl -v http://54.167.135.153/sbsystems-wpatfmaac-ib-64?session-id=2097886607 > tmp.aac
```

### Request Headers
```
GET /sbsystems-wpatfmaac-ib-64?session-id=2097886607 HTTP/1.1
Host: 54.167.135.153
User-Agent: curl/7.43.0
Accept: */*
```
### Response Headers
```
HTTP/1.1 200 OK
Cache-Control: no-cache
Expires: Thu, 01 Jan 1970 00:00:01 GMT
Pragma: no-cache
icy-metaint: 2048
icy-br: 64
icy-name: 93.1 AMOR LA NUEVA
content-type: audio/aacp
```

Thank you again Nathan for building this module.  Even if you don't get time to look into this question I still very much appreciate your work in developing such a helpful module.

Thanks,
Daniel

**Comment by TooTallNate** [comment]
Thanks for the kind words! And as to your issue, I'm sorry, but the server is responsible for sending all metadata events. The client doesn't have any mechanism to request anything additional from the server. Sorry about that!
