### ISSUE TITLE
Getting Track Metadata ?

### ISSUE THREAD

**Issue by daslicht** [TooTallNate/node-icy#27]
Hi,
this returns the  current global stream metadata,
```
 console.error('stat:', res.headers);
```

 how to retrive the song metadata please?
the metadata callback seams to get called never

**Comment by TooTallNate** [comment]
You listen for the "metadata" event (`res.on('metadata', function (metadata) { ... })`). See the README exmaple: https://github.com/TooTallNate/node-icy#example

**Comment by daslicht** [comment]
I know, but it doesnt fire even tho i have metadate....

**Comment by TooTallNate** [comment]
Can you show me the URL of the stream?

**Comment by TooTallNate** [comment]
And/or possibly some code that you are using?

**Comment by daslicht** [comment]
```
var request = require("request")
var url = "http://ansolas.de:8000/status-json.xsl" ;

function getMeta() {
    console.log('tick');
    request({
        url: url,
        json: true
    }, function (error, response, body) {
        if (!error && response.statusCode === 200) {
            //console.log(body) // Print the json response
            //  setTimeout(()=> {
                 
            // },1000);
            console.log('test',body.icestats.source.title) // Print the json response
           
            
        }
    });
    setTimeout(()=> {
        getMeta();
    },250);

}
```

**Comment by daslicht** [comment]
is parsing an ogg stream is supported ?

**Comment by rllola** [comment]
Same here.

I am using ogg stream and it doesn't seems to work.
