### ISSUE TITLE
Promise Support

### ISSUE THREAD

**Issue by FireController1847** [TooTallNate/node-icy#34]
Is it possible to add Promise support to this? As of right now, it's kind of annoying being forced to use a callback, when we could use a promise, and then use async/await to keep everything inline and error catchable. Specifically, promise support for `icy.get`.

**Comment by TooTallNate** [comment]
You can use `util.promisify()` in newer versions of Node.js. Or [`es6-promisify`](https://www.npmjs.com/package/es6-promisify) for older versions.

Patch welcome to introduce promise support directly into this module though!

**Comment by FireController1847** [comment]
Okay I'll make a PR (I had thought I did, whoops!)

**Comment by FireController1847** [comment]
Also, `util.promisify` does not work for the module as it does not return the standard (err, value) but instead returns (value) => value.error. This is why I made this PR, otherwise I would have just done it! haha
